export type User = {
    id: number,
    username: string,
    first_name: string,
    last_name: string,
    patronymicName: string,
    phoneNumber: string,
    email: string,
    gender: string,
    birthDate: string,
    diagnosisDate: string,
    diabetesType: string,
    treatmentType: string,
    imageUrl: string,
}
