export type AppUser = {
    id: number,
    created_at: string,
    updated_at: string,
    last_login: string,
    is_superuser: boolean,
    username: string,
    first_name: string,
    last_name: string,
    email: string | null,
    is_staff: boolean,
    is_active: boolean,
    date_joined: string,
    image: string,
    patronymic_name: string,
    gender: string,
    height: number | null,
    birth_date: string | null,
    diagnosis_date: string | null,
    phone_number: string,
    town: number,
    groups: number[],
    user_permissions: number[],
    moods: number[],
    healths: number[],
    diseases: number[],
}
