export type AppUser = {
    id: number,
    username: string,
    email: string | null,
    last_name: string,
    first_name: string,
    patronymic_name: string,
    imageUrl: string | null,
    gender: string,
    height: number | null,
    birthDate: string | null,
    diabetesType: number | null,
    diagnosisDate: string | null,
    treatmentType: number | null,
    phoneNumber: string,
}
