export const API_URL = import.meta.env.VITE_BACKEND_API_URL
export const USE_MOCKS = import.meta.env.VITE_USE_MOCKS
export const STATUS_CODES = {
    OK: 200,
    CREATED: 201,

    MOVED_PERMANENTLY: 301,

    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    METHOD_NOT_ALLOWED: 405,

    INTERNAL_SERVER_ERROR: 500,
    GATEWAY_TIMEOUT: 504,
}
